name: galleries_api
description: The interface and models for an API providing access to galleries.
version: 1.0.0+1
publish_to: none

environment: 
  sdk: ^3.5.0

dependencies: 
  equatable: ^2.0.5


dev_dependencies:
  flutter_lints: ^4.0.0